### ISSUE TITLE
Please release a new version, because allowlist has been updated

### ISSUE THREAD

**Issue by subnut** [abba23/spotify-adblock#100]
https://github.com/abba23/spotify-adblock/commit/05793f682b5ddfffec26d05e9171fcbe84d729c1 updates the allowlist, but without releasing a new version. This causes distros to not pull in the changes.

**Comment by jclsn** [comment]
Does anyone have a workaround until he reacts?

**Comment by abba23** [comment]
Sorry for the wait, I'm a bit busy currently. A new release with the updated allowlist has now been published.
