### ISSUE TITLE
Error with Make command.

### ISSUE THREAD

**Issue by bassembaraya** [abba23/spotify-adblock#11]
I was using the old project (https://github.com/abba23/spotify-adblock-linux) and it was working fine.
When I tried to install the new one, I got the below error with make command:
`bassem@Bassem:~/spotify-adblock$ make`
`cargo build --profile release`
`cargo build --release`
`make: cargo: Command not found`
`make: *** [Makefile:14: target/release/libspotifyadblock.so] Error 127`

**Comment by abba23** [comment]
Please have a look at the new build prerequisites. You need to install Rust.

**Comment by bassembaraya** [comment]
Thank you so much!
It works now.
I really appreciate your quick response and your wonderful project.
