### ISSUE TITLE
imediately crashes if relaunched 

### ISSUE THREAD

**Issue by dairdevil0420** [abba23/spotify-adblock#121]
i can launch the app and works flawlessly i love it, until i decide to exit out of it and relaunch it. if i use the .desktop it pops up then immediately crashes, and with the LD_PRELOAD command it does the same thing but with this error
[0827/004841.028258:FATAL:gpu_data_manager_impl_private.cc(447)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

the only way that i can re open it is after rebooting my system im running xubuntu 22.04. i have literally only about a single weeks worth of linux knowledge, so message me some commands to run if you need more info.

your wish is my CMD

**Comment by dairdevil0420** [comment]
and it does... well is there any known fixes other than a system reboot?

**Comment by dairdevil0420** [comment]
thank you that worked i was able to even implement it into the .desktop as well

**Comment by dairdevil0420** [comment]
this is a bit off topic but any chance u know anything about the media center Kodi cuz i would love to have it on any os other than the P.O.S that is microsoft windows, and every os i found installs it but never works even slightly.

**Comment by pyro12** [comment]
The thing with kodi is that it is highly dependent on having the correct version of Python3.  Many versions of Linux make frequent updates to Python3 and this can break kodi.  My reluctant solution was to install the flatpak.  This is somewhat limiting as far as access to Local  Network and Directories other than ~/Music and ~/Video and ~/Images, but it can also see mounted drives so you can work with it.

**Comment by dairdevil0420** [comment]
That tempts me to try to dual boot one of those extra light Linux distorts only for Kodi and don't let it update

**Comment by dairdevil0420** [comment]
But please tell me everything u know about the Kodi issue what version of Kodi? Py3? What OS?
