### ISSUE TITLE
Starting problem

### ISSUE THREAD

**Issue by sahafselim** [abba23/spotify-adblock#122]
[sahafselim@sahafselim ~]$ spotify
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[libprotobuf ERROR ../core/vendor/protobuf3/src/google/protobuf/wire_format_lite.cc:577] String field 'spotify.event_sender.proto.DroppedEvents.DroppedEventsBySequenceIdEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[sahafselim@sahafselim ~]$

**Comment by pfuhlert** [comment]
Thank you abba23 that solved the problem for me.

**Comment by sahafselim** [comment]
My problem still alive,I can only open spotify once,for reopen must restart .

**Comment by sahafselim** [comment]
Sorry for misunderstanding,the error message I've posted above is after the second run spotify.
Want to see the error message and run it from terminal for open second time.

**Comment by sahafselim** [comment]
Here's the result 
[sahafselim@sahafselim ~]$ spotify
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0913/125740.516584:FATAL:gpu_data_manager_impl_private.cc(447)] GPU process isn't usable. Goodbye.
İzleme/kesme noktası yakalayıcı (çekirdek döküldü) Tracking/breakpoint catcher (core spilled)
[sahafselim@sahafselim ~]$ spotify --no-zygote
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[sahafselim@sahafselim ~]$

**Comment by 0seno** [comment]
> Since you didn't elaborate, I assume Spotify was launched successfully with the latter command. Just use the same `--no-zygote` option when launching Spotify with spotify-adblock as well then. Either way, this shows that the problem is unrelated to spotify-adblock, so I can't really help you with that if it hasn't already been fixed.

I'm using Ubuntu 22.04.1 LTS, but I'm still a beginner and I wanted to know if it's enough for me to perform as in the youtube tutorial or I need to do more things, since some time has passed
