### ISSUE TITLE
make: *** [Markfile:14: target/release/libspotifyadblock.so] Error 127

### ISSUE THREAD

**Issue by sleepingzzs** [abba23/spotify-adblock#127]
![image](https://user-images.githubusercontent.com/93027509/197251214-34a6027e-4936-409b-9bf4-d3785c88ea46.png)

running the make command while installing gives this error

**Comment by sleepingzzs** [comment]
Ah thanks

**Comment by THEGOLDENPRO** [comment]
I'm getting this same exact error with cargo installed.

![Screenshot_20230429_234347](https://user-images.githubusercontent.com/66202304/235327068-b6796729-ac14-4b3d-b31d-7fd8eefb6be9.png)

cargo is indeed there:
![Screenshot_20230429_234419](https://user-images.githubusercontent.com/66202304/235327084-3f1c8743-834b-4105-9a4a-f5177d687476.png)

**Comment by THEGOLDENPRO** [comment]
okay never mind it's working now and I have no idea how

**Comment by TheArgentinian** [comment]
I had this error for the first time ever after a fresh OS install. You have to exist the terminal and open a new one.  And continue with 
$ cd spotify-adblock
$ make
