### ISSUE TITLE
Can't use the make command on arch

### ISSUE THREAD

**Issue by Aquavortqx** [abba23/spotify-adblock#144]
im using CachyOS Linux x86_64
and my shell is fish 3.6.0

when i cd into the spotify-adblock dir and use the make command i get this error even though rust and cargo are installed

`# cargo build --profile release
cargo build --release
make: cargo: No such file or directory
make: *** [Makefile:14: target/release/libspotifyadblock.so] Error 127`

i think this has something to do with the shell since after installing rust and cargo i got this bunch of text

`To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"`

but i do not know what any of that means...bc im relatively a newbie user and google didnt seem to help too

any help would be much appreciated.

**Comment by Fulcrum21** [comment]
Open a terminal (on most linux systems, you can press the windows button and then type in "terminal" and the first entry will be the terminal application) and then run the command `source $HOME/.cargo/env` after that run the make command again to build the adblocker. If it still gives you the same error, then just restart/shutdown/logout

**Comment by Aquavortqx** [comment]
yooo thanks man...see im very bad at finding solutions for linux using google...thank you a lot for the help <3

have a good one and cheers mate
