### ISSUE TITLE
Home, radio and search page are not loading

### ISSUE THREAD

**Issue by condrove10** [abba23/spotify-adblock#18]
Image link here: https://imgur.com/a/EGHYWEE

**Comment by abba23** [comment]
Are you certain you're using the latest adblocker version? Please provide the terminal output, so I can see what is being blocked.

**Comment by paulmercier-bisq** [comment]
Same problem here, using v1.0.0 released 25 days ago.
Here is terminal output : 
https://ghostbin.co/paste/ay4r3

**Comment by abba23** [comment]
@paulmercier-bisq 
>[*] Error: No config file

The config file should have been copied to `/etc/spotify-adblock/config.toml` when you ran `sudo make install`. Did you do that? Can you check if the file exists?

**Comment by paulmercier-bisq** [comment]
> @paulmercier-bisq
> 
> > [*] Error: No config file
> 
> The config file should have been copied to `/etc/spotify-adblock/config.toml` when you ran `sudo make install`. Did you do that? Can you check if the file exists?

Didn't build from source, just grabbed the .so from Releases.

**Comment by abba23** [comment]
>Didn't build from source, just grabbed the .so from Releases.

Then you'll have to create the config file yourself in [one of the locations specified in the readme](https://github.com/abba23/spotify-adblock#configuration). The default config file can be found [here](https://github.com/abba23/spotify-adblock/blob/main/config.toml).

**Comment by paulmercier-bisq** [comment]
> > Didn't build from source, just grabbed the .so from Releases.
> 
> Then you'll have to create the config file yourself in [one of the locations specified in the readme](https://github.com/abba23/spotify-adblock#configuration). The default config file can be found [here](https://github.com/abba23/spotify-adblock/blob/main/config.toml).

You know sometimes i feel i'm just retarded ... Thanks, should've read the readme more carefully :(

**Comment by condrove10** [comment]
Hi, sorry for the delay, today I read the conversation and rebuilt it from the source and now it's working fine. Again sorry for wasting your time.
