### ISSUE TITLE
Music don't start if "next song" button is pressed

### ISSUE THREAD

**Issue by jvellojin** [abba23/spotify-adblock#19]
Dear developers.

As the tittle says, if I press the "next song" button, the next song is not played. However, the play button says that is playing. After that, the behavior remains when clicking on playlists or other songs. Workarounds are to let the playlist keep playing, or restart Spotify. I have tried to reinstall, with no success.

OS: Arch-Linux
Version: Spotify-adblock installed from source and AUR.

![imagen](https://user-images.githubusercontent.com/47927225/120906293-337fc300-c626-11eb-87f2-5be940b5c6f2.png)

**Comment by abba23** [comment]
Can you provide the terminal output from when this happens? Have you checked if this really only happens with the adblocker and not when launching Spotify normally?

**Comment by jvellojin** [comment]
If I start Spotify normally, the issue is not present and the button works ok. Below is the terminal output when running spotify with spotify-adblock, pressing the "next song" button, and three attempts to play any song (without success).

`/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[*] Config file: /etc/spotify-adblock/config.toml
[+] cef_urlrequest_create:	 https://apresolve.spotify.com/?time=1622931543&type=accesspoint
[*] Config file: /etc/spotify-adblock/config.toml
[+] getaddrinfo:		 apresolve.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[+] getaddrinfo:		 login5.spotify.com
[+] getaddrinfo:		 guc3-accesspoint-d-8bwp.ap.spotify.com
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] getaddrinfo:		 spclient.wg.spotify.com
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playlist/v2/user/clomutt0w74e1uiuqrqrog4ys/rootlist?decorate=revision%2Cattributes%2Clength%2Cowner&from=0&length=120
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/socialgraph/v2/dismissed/artist?include_timestamps=true&count=1000&source_uri=spotify%3Auser%3Aclomutt0w74e1uiuqrqrog4ys
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/ad-logic/state/config
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExNTYwMDU5NSAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiZTNkNDI1NWYtYTQyZi00YzQ2LTgzMzktMDUzZTUzOTQ1OTJlIn0=
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/device-capabilities/v1/capabilities?device_type=computer&client_id=65b708073fc0480ea92a077233ca87bd&device_model=&device_brand=&client_version=1.1.56.595.g2d2da0de
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/social-connect/v2/sessions/current
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playlist/v2/playlist/37i9dQZF1E370RyWVcXEfZ/diff?revision=27048002%2C000000000530f3d0fe558d5a2d19c7f9f5adceda&handlesContent=
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playlist/v2/user/clomutt0w74e1uiuqrqrog4ys/rootlist/diff?revision=3%2C68ad04cfd201ef6584e185ea3e94f3dd0879bb58&handlesContent=
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] getaddrinfo:		 spclient.wg.spotify.com
[+] getaddrinfo:		 spclient.wg.spotify.com
[-] getaddrinfo:		 sentry.io
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] getaddrinfo:		 dealer.spotify.com
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/ads/v1/ads/hpto?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExNTYwMDU5NSAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiZTNkNDI1NWYtYTQyZi00YzQ2LTgzMzktMDUzZTUzOTQ1OTJlIiwicmVxdWVzdF9pZCI6IjgyMGYyZWUxLTM1MDktNDNmNC1iMjcxLTQ0ZTNhMmI3ZDZmYiIsInBvZCI6eyJjb250ZXh0IjoxLCJzZXNzaW9uIjoxfSwib3ZlcnJpZGVzIjp7fSwidGFyZ2V0aW5nIjp7InBsYXliYWNrX2lkIjoiODIwZjJlZTEtMzUwOS00M2Y0LWIyNzEtNDRlM2EyYjdkNmZiIiwiYWRicmVhayI6InZpZGVvLGFkc2NvcmUiLCJhZHBvZCI6IjEiLCJhcnRpc3QiOiI0VTdsWHlLZFNmMUpiTTFhWHZzb2RDIiwiY29udGV4dCI6InNwb3RpZnk6cGxheWxpc3Q6MzdpOWRRWkYxRTM3MFJ5V1ZjWEVmWiIsImZlYXR1cmUiOiJkZXNrdG9wLWNsaWVudC14IiwiZm9jdXMiOiJ0cnVlIiwidHJhY2siOiJzcG90aWZ5OnRyYWNrOjJETnlaUDRQeTZmNHpNQVNMQm5JdTYifX0=
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] getaddrinfo:		 dealer.spotify.com
[+] getaddrinfo:		 guc-spclient.spotify.com
[+] getaddrinfo:		 api.spotify.com
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/social-connect/v2/sessions/current
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/device-capabilities/v1/capabilities?device_type=computer&client_id=65b708073fc0480ea92a077233ca87bd&product_id=&device_model=&device_brand=&client_version=1.1.56.595.g2d2da0de
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/facebook/config
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/socialgraph/v2/dismissed/artist?include_timestamps=true&count=1000&source_uri=spotify%3Auser%3Aclomutt0w74e1uiuqrqrog4ys
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/recently-played/v3/user/clomutt0w74e1uiuqrqrog4ys/recently-played?limit=50&filter=default,track,collection-new-episodes
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/played-state/v1/items?fromTimestamp=1622929137547
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/collection/v2/delta
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/collection/v2/delta
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/collection/v2/delta
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/collection/v2/delta
[+] getaddrinfo:		 guc-dealer.spotify.com
[+] getaddrinfo:		 dealer.spotify.com
[+] getaddrinfo:		 dealer.spotify.com
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] getaddrinfo:		 misc.scdn.co
[+] getaddrinfo:		 seeded-session-images.scdn.co
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/played-state/v1/updates
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/social-connect/v2/sessions/current
[+] getaddrinfo:		 i.scdn.co
[+] getaddrinfo:		 xpui.app.spotify.com
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playplay/v1/key/ef4921ed3667be04c024efbc97ca3001d9471df4
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playlist/v2/playlist/37i9dQZF1E35eoGucDc0TU/diff?revision=27048002%2C000000000d894d62ab0aea7660f42a754c00b100&handlesContent=
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/net-fortune/v2/fortune
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playplay/v1/key/4bad1b7d56e071ac9373eaaee8d3c9adcd8c7b4d
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/net-fortune/v2/fortune
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playplay/v1/key/e67b17b0881f901cc92fee3b20f057bee370b0ae
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/context-resolve/v1/spotify:show:5neP2EhnGnHK0FWek2osI5?include_video=true
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/net-fortune/v2/fortune
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[+] cef_urlrequest_create:	 https://heads-fa.scdn.co/head/f0acc482194d279028752a7ce09e36a32f77f92b
[+] getaddrinfo:		 heads-fa.scdn.co
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playplay/v1/key/f0acc482194d279028752a7ce09e36a32f77f92b
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/storage-resolve/v2/files/audio/interactive/0/f0acc482194d279028752a7ce09e36a32f77f92b?product=0
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/played-state/v1/items
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/padme/v2/metadata/fileId/f0acc482194d279028752a7ce09e36a32f77f92b
[+] cef_urlrequest_create:	 https://audio-ak-spotify-com.akamaized.net/audio/f0acc482194d279028752a7ce09e36a32f77f92b?__token__=exp=1623017967~hmac=4c719c5d31c26765643762f8dec3f60959498d91e9c43e7a08e4b67a093043e0
[+] getaddrinfo:		 audio-ak-spotify-com.akamaized.net
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/played-state/v1/items?fromTimestamp=1622929137547
[+] cef_urlrequest_create:	 https://audio-ak-spotify-com.akamaized.net/audio/f0acc482194d279028752a7ce09e36a32f77f92b?__token__=exp=1623017967~hmac=4c719c5d31c26765643762f8dec3f60959498d91e9c43e7a08e4b67a093043e0
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/connect-state/v1/devices/b0dd4fe5e33374288af145d085c1715fa355818f
[+] cef_urlrequest_create:	 https://audio-ak-spotify-com.akamaized.net/audio/f0acc482194d279028752a7ce09e36a32f77f92b?__token__=exp=1623017967~hmac=4c719c5d31c26765643762f8dec3f60959498d91e9c43e7a08e4b67a093043e0
[+] cef_urlrequest_create:	 https://audio-ak-spotify-com.akamaized.net/audio/f0acc482194d279028752a7ce09e36a32f77f92b?__token__=exp=1623017967~hmac=4c719c5d31c26765643762f8dec3f60959498d91e9c43e7a08e4b67a093043e0
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/storage-resolve/v2/files/audio/interactive_prefetch/0/311beb0b396835361d0922dd5e4b357bd8cd9c84?product=0
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/playplay/v1/key/311beb0b396835361d0922dd5e4b357bd8cd9c84
[+] cef_urlrequest_create:	 https://audio-ak-spotify-com.akamaized.net/audio/311beb0b396835361d0922dd5e4b357bd8cd9c84?__token__=exp=1623017972~hmac=fa51c448784b072ad6b3dafb997614171e52d639f72db47c346cc8956a698429
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/net-fortune/v2/fortune?bandwidth=7029622
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/user-customization-service/v1/customize
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[-] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
`

**Comment by abba23** [comment]
I don't see anything in that log being blocked that shouldn't be. I do appear to have the same problem when launching Spotify without the adblocker though. After a fresh start I can only play a single track. This might just be a temporary problem on Spotify's end.

My other guess would be that it's related to a recent Arch Linux package update? Do you by any chance use pipewire?

**Comment by jvellojin** [comment]
Indeed, I'm using pipewire-pulse instead of pulseaudio. Never thought that could be the problem...

**Comment by abba23** [comment]
I'll close this issue then, since the problem appears to be unrelated to adblocking. For reference, restarting the PipeWire service (i.e. `systemctl --user restart pipewire.service`) and Spotify reliably fixes the problem for me.

**Comment by jvellojin** [comment]
Agree. Thank you.

**Comment by abba23** [comment]
Should be fixed now.

* https://bugs.archlinux.org/task/71158
* https://github.com/archlinux/svntogit-packages/commit/d4f0b0d1fa692e4fed9f773e3cb7fa6e3bcccb1f

**Comment by jvellojin** [comment]
Indeed, the problem has disappeared. On the other hand, I would like to thank you and thank the other developers for this program.
