### ISSUE TITLE
pop-up ads

### ISSUE THREAD

**Issue by MeowyAsh** [abba23/spotify-adblock#21]
would it be possible to get rid of these too?

**Comment by abba23** [comment]
I don't remember seeing any pop-up ads myself, but if they're currently getting through, then it's unlikely that they can be blocked with this adblocker (i.e. by blocking access to domains and URLs). You could probably do it in a similar way to what is outlined in #12 though.

**Comment by nonvieri** [comment]
same here

**Comment by MeowyAsh** [comment]
> I don't remember seeing any pop-up ads myself, but if they're currently getting through, then it's unlikely that they can be blocked with this adblocker (i.e. by blocking access to domains and URLs). You could probably do it in a similar way to what is outlined in #12 though.
> 
> Edit: Untested, but just looking at `xpui.js`, searching for `modal",default:!0` and replacing it with `modal",default:false` for example might work.

really sorry, realized i had the regular spotify pinned to my dock and was using that instead. i'll close the issue
