### ISSUE TITLE
Error 101 in Make process

### ISSUE THREAD

**Issue by animercy** [abba23/spotify-adblock#22]
Using OpenSUSE TW. I have Rust installed. Still getting error in the `make` command.
Output of the `make` command is given below:

`> make`
`# cargo build --profile release`
`cargo build --release`
`   Compiling proc-macro2 v1.0.27`
`   Compiling syn v1.0.73`
`   Compiling serde_derive v1.0.126`
`   Compiling memchr v2.4.0`
`error: linker 'cc' not found
  |
  = note: No such file or directory (os error 2)`

`error: aborting due to previous error`

`error: could not compile 'memchr'`

`To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...`
`error: linker 'cc' not found
  |
  = note: No such file or directory (os error 2)`

`error: aborting due to previous error`

`error: linker 'cc' not found
  |
  = note: No such file or directory (os error 2)`

`error: aborting due to previous error`

`error: linker 'cc' not found
  |
  = note: No such file or directory (os error 2)`

`error: aborting due to previous error`

`error: build failed`
`make: *** [Makefile:14: target/release/libspotifyadblock.so] Error 101`

**Comment by abba23** [comment]
You'll need to install a linker (e.g. by installing gcc), because Rust doesn't come with its own.

**Comment by animercy** [comment]
That worked! May be, mention it in the README? - totally up to you.
Thanks for your work.
