### ISSUE TITLE
bash: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free

### ISSUE THREAD

**Issue by MuhammedTaha02** [abba23/spotify-adblock#23]
![image](https://user-images.githubusercontent.com/62564400/122690778-0b05e480-d234-11eb-8575-2fc9233ddff9.png)

OS: Fedora 34
Kernel: 5.12.11-300.fc34.x86_64
Spotify Version: 1.1.56.595.g2d2da0de_amd64.deb "LPF-Spotify"

**Comment by abba23** [comment]
See #2.
