### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by ClemGlacee** [abba23/spotify-adblock#24]
When trying to use `$ flatpak run --command=sh com.spotify.Client -c 'eval "$(sed s#LD_PRELOAD=#LD_PRELOAD=$HOME/.spotify-adblock/spotify-adblock.so:#g /app/bin/spotify)"'`

```
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/sadsoup/.spotify-adblock/spotify-adblock.so)
```

**Comment by abba23** [comment]
As noted in the readme, this might not work with the Flatpak Spotify version depending on your system's libraries. This is one such case. The glibc version on the system where you compiled the adblocker is incompatible with the one that comes with the Flatpak package.

A workaround would be compiling on a different system that has the same glibc version as the Flatpak package. Or you could try the prebuilt binary from the [releases page](https://github.com/abba23/spotify-adblock/releases) (just replace `~/.spotify-adblock/spotify-adblock.so` with it).

**Comment by ClemGlacee** [comment]
Yeah I noticed that but wanted to give it a shot anyway, also wanted to give you the error in case you'd need it for something

Thanks I will try that :)
