### ISSUE TITLE
Random Failure on Gnome (pop-os)

### ISSUE THREAD

**Issue by sepehr-gh** [abba23/spotify-adblock#25]
I have been using this on **Kubuntu** for a long time and it was working great, no problems what so ever.

Yesterday I tried using it on **Pop-Os! 21.04** and there was an issue which I could listen to songs for quite some time in the beginning but then suddenly songs that were not in my cache were out of reach and every song were gray on Spotify, not allowing me to go to next song or choose anything from any playlist or album. 

I thought its being an internet issue, but once I ran it without adblock it was alright and I could keep listening for ever.

Today I am on KDE again and no such issue.

### How to reproduce:
1. install pop-os 21
2. build and install
3. create new desktop file for spotify-adblock (as said in the tutorials)
4. lunch spotify from newly created desktop file
5. keep listening to music till at some point it will all go gray (perhaps you will need to keep the spotify in background and do something else?)

**Comment by abba23** [comment]
My first guess would be that the configuration file can't be loaded for some reason, causing the whitelist to be empty and thus almost everything to be blocked. Does Pop-Os maybe use some packaging framework (like Flatpak) by default, that restricts the file system access of installed applications?

Please try launching Spotify with the adblocker from a terminal and check if it says that a config file has been found (e.g. `[*] Config file: /etc/spotify-adblock/config.toml`) at the top.

**Comment by sepehr-gh** [comment]
I will have to try this on a VM since I don't have Pop-Os installed right now.
