### ISSUE TITLE
How can I override the default Spotify launcher with the modified one?

### ISSUE THREAD

**Issue by nonvieri** [abba23/spotify-adblock#32]
can you pls tell me how can i replace the official launcher with the adblocked launcher so it launches as default?

**Comment by abba23** [comment]
This is a general Linux/freedesktop question that you should have been able to answer by using an internet search engine of your choice. Just name the new `.desktop` file the same as the original one (probably `spotify.desktop`) and place it in `~/.local/share/applications`.
