### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by prorounak2005** [abba23/spotify-adblock#38]
Hi I am new to linux so I am not able to understand how to install this Spotify adblocker in my linux mint os. Can any one help me with it ? :(

**Comment by abba23** [comment]
I'm sorry, but this really isn't the right place for general Linux support. The instructions should be easy enough to follow if you know how to type things into a terminal and install software. If you don't know how to do that, please consult an internet search engine of your choice.

**Comment by prorounak2005** [comment]
OH MY GOD IT IS WORKING !!!!!!!!! Thank u for making this I really liked it :) Now I can listen to spotify without ads and withut getting tarcked. :+1:
