### ISSUE TITLE
Cannot listen to any audio or login

### ISSUE THREAD

**Issue by Snephanie** [abba23/spotify-adblock#43]
When preloading with the supplied command and binary, it blocks login5.spotify.com so I can't login/listen to any audio and I cannot find the config.toml file.

Info:
Kernel: 5.10.61-1-MANJARO
OS: Manjaro Linux x86_64
Spotify: spotify 1:1.1.67.586-1 from official repos
Memory: 6011MiB / 15948MiB
CPU: Intel i7-4770 (8) @ 3.900GHz
Shell: bash 5.1.8

**Comment by abba23** [comment]
Can you check if the configuration file `/etc/spotify-adblock/config.toml` exists? It should have been created when you ran `sudo make install`.

**Comment by Snephanie** [comment]
It does not exist, no.

**Comment by Snephanie** [comment]
Sorry about that, as it turns out I'm a little braindead.
