### ISSUE TITLE
Spotify adblock with spotifywm-git

### ISSUE THREAD

**Issue by nolbap** [abba23/spotify-adblock#44]
I'm in arch linux and have been using spotify adblock for a long time and today while setting up xmonad I came across spotifywm-git (aur) program which let's you set up spotify on a certain workspace because how spotify is built doing that doesn't normally work. The thing is, if I try to use the two together it gives me this error:

`/bin/sh: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free`

I know this isn't really related to this app but I don't know how I could fix this issue myself...

**Comment by abba23** [comment]
>`/bin/sh`

I think the problem is that you're running `sh` with `spotify-adblock.so` preloaded. It should work if you just do `LD_PRELOAD="<path to>/spotify-adblock.so <path to>/spotifywm.so" spotify`.

**Comment by nolbap** [comment]
I just tried it and it fixed the issue! Thanks a lot for your time!
