### ISSUE TITLE
Is there a way to get rid of the big empty box at the bottom?

### ISSUE THREAD

**Issue by realnc** [abba23/spotify-adblock#56]
This is more a question than a bug. Ever since spotify started forcing their new UI, there's a big empty box in it:

![image](https://user-images.githubusercontent.com/1665903/144191456-dbaf9ad9-6b02-4937-96ee-b5c30f9016a5.png)

Has anyone found a way to get rid of it? In the older versions of spotify, if you blocked the right requests, the box would disappear.

**Comment by abba23** [comment]
See the pinned issue (#12).
