### ISSUE TITLE
is it possible to as a md file with the list of file urls to be Banned ?

### ISSUE THREAD

**Issue by CarlosEmanuelMartins** [abba23/spotify-adblock#59]
Is it possible to as a md file with the list of file urls to be Banned. If so one could add the urls to etc/hosts and make a "quick fix" that would work with the snap version of spotify as well other version of the program. Presumably with no downsides.

**Comment by abba23** [comment]
That wouldn't work, because you can only stop proper DNS resolution like that, i.e. block domains, not URLs.
