### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by kaneru-soju** [abba23/spotify-adblock#6]
I installed by following the steps, but for some reason the spotify client is extremely zoomed out. Everything is tiny and I would like to know how to fix that if possible. Thanks!

**Comment by Greatest125** [comment]
Could this be an issue with your computer? I also installed following the steps and I have no issue...

Maybe reinstall the Spotify client?

**Comment by abba23** [comment]
Just to make sure, this doesn't happen when you launch Spotify normally? I don't see how this problem could be related to the adblocker.

If you have a HiDPI display, you can try launching Spotify with the `--force-device-scale-factor=1.25` option.

**Comment by kaneru-soju** [comment]
> Could this be an issue with your computer? I also installed following the steps and I have no issue...
> 
> Maybe reinstall the Spotify client?

Oh, it actutally seems like the regular spotify client is zoomed out as well for some reason. Weird. It wasn't like that when I installed the Spotify app through the Popshop (Pop-OS).



> Just to make sure, this doesn't happen when you launch Spotify normally? I don't see how this problem could be related to the adblocker.
> 
> If you have a HiDPI display, you can try launching Spotify with the `--force-device-scale-factor=1.25` option.

I'll try this and edit later when I can see if it works. Thanks for the suggestion.

**Comment by abba23** [comment]
>If I were to do this with the .desktop file... where would I put it?

Just after `spotify` in the `Exec` line. I.e.:

`Exec=env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify --force-device-scale-factor=1.25 %U`

**Comment by kaneru-soju** [comment]
> > If I were to do this with the .desktop file... where would I put it?
> 
> Just after `spotify` in the `Exec` line. I.e.:
> 
> `Exec=env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify --force-device-scale-factor=1.25 %U`

I think I managed to figure out the issue. Spotify is only super zoomed out if I have fractional scaling turned on for my display and change it to 125% (or any other increment of 25). If I have it at 100% or 200%, it's fine. Unfortunately 100% is too small for me, and 200% is too large. I suppose I won't be able to fix the problem.

The option you listed doesn't work if I have my display scaling at 125%. Thanks for the help though!
