### ISSUE TITLE
spoitify not open witch adblock on Fedora 35 

### ISSUE THREAD

**Issue by GabrielAraujoDiaz** [abba23/spotify-adblock#64]
when I try to open it via the command line, this error appears:
/usr/bin/sh: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free

**Comment by abba23** [comment]
See #2.

**Comment by GabrielAraujoDiaz** [comment]
I tried using the flatpak version but it starts spotify on a white screen even without adblock

**Comment by GabrielAraujoDiaz** [comment]
would it be better to change the distribution? which would you recommend?

**Comment by RaameshB** [comment]
you have to modify the spotify exec instead
as abba23 said, read #2, more specifically the end of it

(im talking about the rpm fusion version of the spotify client)

**Comment by RaameshB** [comment]
Also it doesn't seem to work with the flatpak version anyways (for Fedora 35)
I believe it's a dependency version mismatch (flatpak bundles its own dependencies). I'm pretty sure GLIBC is the package that's causing issues.
