### ISSUE TITLE
Refering to #57, what does someone have to remove to get rid of the "UPGRADE" button?

### ISSUE THREAD

**Issue by RaptaG** [abba23/spotify-adblock#66]
It's a question actually, not a bug, I just wanted to ask..
If possible, can I have some help?

**Comment by abba23** [comment]
I'm sorry, but this is the wrong place for what you're trying to do. As I already said in that other issue, this project is about blocking network connections, not modifying the user interface. The upgrade button is also neither ad-related nor particularly annoying in my opinion.
