### ISSUE TITLE
whenever i try to play a song in a playlist getting an error "this content is not available"

### ISSUE THREAD

**Issue by Rishabh672003** [abba23/spotify-adblock#67]
![image](https://user-images.githubusercontent.com/53911515/146870024-f5bc453c-5b69-4bf8-bc39-e2703c341dbd.png)

i even reinstalled the spotify app and adblock still the problem persist

**Comment by tomast1337** [comment]
This is happening here for a few days too, will be any fixes?

**Comment by tomast1337** [comment]
> This is happening here for a few days too, will be any fixes?

Oh, i just saw the others issues🤦, i think it is similar #60, after reinstalling it is not working again.

**Comment by Rishabh672003** [comment]
> > This is happening here for a few days too, will be any fixes?
> 
> Oh, i just saw the others issuesfacepalm, i think it is similar to #60, after reinstalling it is not working again.

i installed the git version and  now it is working

**Comment by nemoforum** [comment]
Happened to ma again.
Fixed by adding:
`+    'ap-g.*\.spotify.com',
`
