### ISSUE TITLE
Can't play single tracks from a list.

### ISSUE THREAD

**Issue by abinlatheef** [abba23/spotify-adblock#69]
**Can't:**
All tracks (in a playlist or album) are shown faded and shows content not available when clicked. 
**Can:**
We can play by clicking the play button of a whole playlist or from the player controls at the bottom. Can't select songs from queue too.

 Spotify works fine if we don't use the adblock (without using the LDPRELOAD thingy).

![image](https://user-images.githubusercontent.com/63762448/147041947-d86aa4a2-28bf-43f9-abf3-6c7e6dd35540.png)

**Comment by Syzygianinfern0** [comment]
Reinstall

**Comment by abinlatheef** [comment]
Thanks. Sorry for not looking closed issues first.
