### ISSUE TITLE
All my songs are grayed out when launching spotify with spotify-adblock

### ISSUE THREAD

**Issue by swaggyP36000** [abba23/spotify-adblock#70]
![Screenshot](https://user-images.githubusercontent.com/45519513/147306781-20ddcdb2-4915-429c-8fbc-e23bf224434e.png)

When I launch the regular spotify client, it works just fine, but when I launch spotify-adblock it gives me this issue. Is there any fix?

I have tried restarting wifi and enabling/disabling VPN but that didn't help

**Comment by dipzza** [comment]
Hi, a lot people were having the same problem but abba fixed it really fast.

Try to reinstall <code>spotify-adblock-git</code>, if not working check #60 and #7.

**Comment by swaggyP36000** [comment]
This worked, thanks!
