### ISSUE TITLE
Can't play songs from playlists - Ubuntu 20.04

### ISSUE THREAD

**Issue by ayoob-portfolio** [abba23/spotify-adblock#71]
All songs are greyed out but I can play albums using the play button. Using the latest version, installed from source

![image](https://user-images.githubusercontent.com/87142880/147512616-0d860ba0-0462-418e-a544-03d3e4f3c1fa.png)
![image](https://user-images.githubusercontent.com/87142880/147512717-ca1f0b37-f6b0-4654-aa51-45a5dd3ebd78.png)
![image](https://user-images.githubusercontent.com/87142880/147512640-8746a4bc-c91d-4170-bb22-b714b9e07fa3.png)
![image](https://user-images.githubusercontent.com/87142880/147512661-1dca8012-b818-4b9e-8508-cf4dc494bd08.png)

**Comment by Syzygianinfern0** [comment]
#60

**Comment by ayoob-portfolio** [comment]
Yes, I updated to the latest version

**Comment by abba23** [comment]
It looks like you created a custom config file in `~/.config/spotify-adblock/config.toml`, which takes precedence over the default one in `/etc/spotify-adblock/config.toml`. Only the latter would have been updated when you installed the latest version. You'll need to either delete that custom config file or manually modify it to include the latest change.

**Comment by ayoob-portfolio** [comment]
That fixed it, thanks for the help :)
