### ISSUE TITLE
Spotify adblock for flatpak won't launch at all

### ISSUE THREAD

**Issue by jgsource** [abba23/spotify-adblock#72]
Could this be because I am using opensuse tw? Cause this app worked for me using arch linux.

**Comment by th1nhhdk** [comment]
Same here on `Fedora 35`

![image](https://user-images.githubusercontent.com/58503327/148497654-5ddd79ae-9feb-4010-89db-e5aef77de93a.png)

**Comment by abba23** [comment]
See the pinned issue #24.
