### ISSUE TITLE
Autoupdate config.toml definitions

### ISSUE THREAD

**Issue by labgua** [abba23/spotify-adblock#73]
Thank You for this project, beautiful idea to wrap the spotfy library!!! :)

A few days ago I had some problems with the app and looking at the project I realized that the definitions of config.toml are updated.
I thought: "it wouldn't be nice if you could update them automatically every time you open spotify!"

A small start bash script before starting the program could check if the definition config.toml is the same on git. In case it is different it could overwrite it.

I'm not familiar with pull request, so I leave you here a small example of code that could do this 
(with a litle problem of write permission in etc file... and so I think it is more appropriate to give priority to the definition in home and then to the definition in /etc/ ...)

```bash

# start.sh

# generate sha of local def
LOCAL_DEF_SHA=$(cat /etc/spotify-adblock/config.toml | openssl dgst -sha256)

# generate sha of local def
REMOTE_DEF_SHA=$(curl https://raw.githubusercontent.com/abba23/spotify-adblock/main/config.toml | openssl dgst -sha256)

# if they are different, download from git ..
if [ "$LOCAL_DEF_SHA" != "$REMOTE_DEF_SHA" ]; then
    echo "LOCAL != REMOTE, UPDATE definitions ..."
    curl -o /etc/spotify-adblock/config.toml https://raw.githubusercontent.com/abba23/spotify-adblock/main/config.toml 
else
    echo "LOCAL == REMOTE, OKK"
fi

#run spotify
LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify
```

**Comment by labgua** [comment]
Checking the content instead of the SHA is fine, ok. (Finally the content will always be small....)

So to the redownload question...I preferred to redownload it to avoiding the lost formatting of the file caused by the `curl -s` command (I had already tried at the time).
In `toml` format I don't knew if it could be a problem...

**Comment by abba23** [comment]
While such a script might be convenient for some people, I don't think it should be a default or even recommended, since there's no guarantee that a newer default config will be compatible with an older version of spotify-adblock.

It also adds additional dependencies (not every distribution has `openssl` or `curl` installed by default), in its current state requires elevated privileges to write the new file and could even break the current configuration if Github for some reasons returned something like a 503 HTTP error page instead.

Personally, I generally dislike automatic background updates that potentially change a program's behavior without my explicit permission.

**Comment by atatdotdot** [comment]
Apologies @abba23, I wasn't suggesting that this should be included as a default, and I agree that it ought to have more error checking, but I thought it could perhaps go into a utils directory, or be included in the documentation as a suggested script the user could create themselves.

@labgua, not sure why you were having trouble with losing formatting; the version I posted does not lose any formatting, as shown here:

```
:~$ curl -s -o t1 https://raw.githubusercontent.com/abba23/spotify-adblock/main/config.toml
:~$ O=$(curl -s https://raw.githubusercontent.com/abba23/spotify-adblock/main/config.toml); cat <<< "$O" > t2;
:~$ diff t1 t2
:~$
```

No output from diff, showing files are identical.

**Comment by abba23** [comment]
I'm sorry, but I strongly suspect that suggesting people fiddle around with additional scripts like this would increase the number of issues I'd have to deal with rather than alleviate it, so I'm not going to include it.

**Comment by atatdotdot** [comment]
> I'm sorry, but I strongly suspect that suggesting people fiddle around with additional scripts like this would increase the number of issues I'd have to deal with rather than alleviate it, so I'm not going to include it.

A wise decision, all things considered. :-)

**Comment by milahu** [comment]
im using this wrapper script to autoupdate my config.toml

```sh
#! /usr/bin/env bash
echo "updating spotify blocklist in $HOME/.config/spotify-adblock/config.toml"
echo "to disable updates, run: touch $HOME/.config/spotify-adblock/dont-update"
echo "to view the update history, run: ( cd $HOME/.config/spotify-adblock && git log )"
#set -x # debug
[ ! -d $HOME/.config/spotify-adblock ] && mkdir -p $HOME/.config/spotify-adblock
(
  cd $HOME/.config/spotify-adblock
  if [ ! -e dont-update ]; then
    export GIT_AUTHOR_NAME=nobody
    export GIT_AUTHOR_EMAIL=
    export GIT_COMMITTER_NAME=nobody
    export GIT_COMMITTER_EMAIL=
    [ ! -d .git ] && git init
    curl -O https://raw.githubusercontent.com/abba23/spotify-adblock/main/config.toml
    git add config.toml
    git commit -a -m "update config.toml" || true
  fi
)
export LD_PRELOAD=/usr/lib/libspotifyadblock.so
exec spotify
```

> there's no guarantee that a newer default config will be compatible with an older version of spotify-adblock

in that case, the user can rollback with

```sh
cd $HOME/.config/spotify-adblock
git checkout HEAD^ # go back one version
touch dont-update
```
