### ISSUE TITLE
make not working 

### ISSUE THREAD

**Issue by karimo0** [abba23/spotify-adblock#75]
when i type make it gives me this
[🔍] × make
cargo build --profile release
cargo build --release
make: cargo: No such file or directory
make: *** [Makefile:14: target/release/libspotifyadblock.so] Error 127

**Comment by abba23** [comment]
You need to install [Cargo](https://doc.rust-lang.org/cargo/). I assumed it came with Rust on all distributions, but apparently that's not the case. I've just added it to the build prerequisites.
