### ISSUE TITLE
Spotify adblock does NOT work at all on LM20

### ISSUE THREAD

**Issue by harrwester** [abba23/spotify-adblock#76]
Last January I installed Spotify on my LM20 from https://www.spotify.com/us/download/linux/ as .deb and it was working. Then I installed the adblock according to the instructions as follows:

_$ git clone https://github.com/abba23/spotify-adblock.git
$ cd spotify-adblock
$ make
$ sudo make install_

and I even created a desktop shortcut utilizing _env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify %U_ command and it was working ad-free for a couple of weeks until it wasn't (probably due to some system update or who knows) and I couldn't make it run even without adblock - just the official free spotify...sometimes it crashed and other times it just got a black screen so since I wasn't able even to launch spotify, I removed it all.

Yesterday, after almost a year I tried again and installed spotify (from spotify.com as .deb) and adblock too so I can launch official free spotify with ads, but when I try to launch adblock from desktop shortcut I have the same issue as last year - it says "Something went wrong, try reloading the page". Now, what I get since yesterday more often while trying to launch the spotify-adblock the home page has 3 dots in the middle of the screen as if loading but it never does and the songs and everything is greyed out and when trying to launch it from the terminal, I get:

_mint@harwester:~$ LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify
[*] Config file: config.toml
[*] Error: Read config file (Is a directory (os error 21))
[-] getaddrinfo:		 dealer.spotify.com
[2022/01/06 13:04:27:4519] ERR: getaddrinfo failed: -4
[-] getaddrinfo:		 dealer.spotify.com
[2022/01/06 13:04:28:0536] ERR: getaddrinfo failed: -4
[-] getaddrinfo:		 dealer.spotify.com
[2022/01/06 13:04:29:5569] ERR: getaddrinfo failed: -4
[+] cef_urlrequest_create:	 https://apresolve.spotify.com/?time=1641470667&type=accesspoint
[+] cef_urlrequest_create:	 https://spclient.wg.spotify.com/gabo-receiver-service/public/v3/events/
[*] Config file: config.toml
[*] Error: Read config file (Is a directory (os error 21))
[-] getaddrinfo:		 spclient.wg.spotify.com
[-] getaddrinfo:		 apresolve.spotify.com
[-] getaddrinfo:		 ap.spotify.com
[-] getaddrinfo:		 ap.spotify.com
[-] getaddrinfo:		 ap.spotify.com
[-] getaddrinfo:		 ap.spotify.com
[-] getaddrinfo:		 ap.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[-] getaddrinfo:		 dealer.spotify.com
[2022/01/06 13:04:30:5087] ERR: getaddrinfo failed: -4
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[-] getaddrinfo:		 apresolve.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[-] getaddrinfo:		 dealer.spotify.com
[2022/01/06 13:04:31:1100] ERR: getaddrinfo failed: -4
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[-] getaddrinfo:		 dealer.spotify.com
[2022/01/06 13:04:32:6637] ERR: getaddrinfo failed: -4
[-] getaddrinfo:		 ap.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login
[-] getaddrinfo:		 login5.spotify.com
[-] getaddrinfo:		 apresolve.spotify.com
[+] cef_urlrequest_create:	 https://login5.spotify.com/v3/login_

![Screenshot from 2022-01-06 13-19-44](https://user-images.githubusercontent.com/77215984/148382242-54c8c9b9-adbf-4dff-b7da-cddc534fa481.png)

![Screenshot from 2022-01-06 13-08-23](https://user-images.githubusercontent.com/77215984/148381527-a4a424fb-8153-400f-9085-2e8f0b9d56a0.png)

**Comment by abba23** [comment]
I don't know what "LM20" is, but this looks like your config file can't be read.

>Config file: config.toml
>Error: Read config file (Is a directory (os error 21))

Do you perhaps for some reason have a directory called `config.toml` in your working directory? If so, try deleting it or changing your working directory, so it loads the correct config file from `/etc/spotify-adblock/config.toml`.

**Comment by harrwester** [comment]
ok, it worked out well, thanks! I indeed had a folder named config.toml in the working directory (home), it was empty and was there for a while for no reason. btw, LM20 is linux mint v20.
