### ISSUE TITLE
[ proposal ] hide Episodes for you section

### ISSUE THREAD

**Issue by chiboreache** [abba23/spotify-adblock#78]
would be REALLY nice!

**Comment by abba23** [comment]
I'm sorry, but this is the wrong place for what you're trying to do. This project is about blocking network connections, not modifying the user interface.

**Comment by chiboreache** [comment]
already found solution, sorry for bothering mate =)

https://github.com/theRealPadster/spicetify-hide-podcasts/blob/main/README.md
