### ISSUE TITLE
Will this work with spicetify?

### ISSUE THREAD

**Issue by AayanTDE** [abba23/spotify-adblock#8]
Is this compatible with [spicetify](https://aur.archlinux.org/packages/spicetify-cli)? Can i just install it from the AUR and it'll be ready to go?

**Comment by abba23** [comment]
Probably. Why don't you just try it out? Depending on the apps you want to use, you might need to add some exceptions to the allowlist though.

**Comment by system32uwu** [comment]
Updates on this @AayanTDE ? Did it work for you?

**Comment by dswapnil104** [comment]
@yanNotDev what was the status follow-up on this issue ? 
Is it known to work with Spicetify-utility finally ?
