### ISSUE TITLE
Spotify crashes on execution

### ISSUE THREAD

**Issue by PixelMelt** [abba23/spotify-adblock#82]
If you run spotify through a .desktop file without leaving the terminal argument set to true it will crash, however running it with the window open lets it proceed as usual.
kubuntu 21.04 kernel 5.11.0-46-generic

**Comment by PixelMelt** [comment]
this is my fix for now.

replace spotify.desktop with the following


[Desktop Entry]
Type=Application
Name=Spotify(adblock)
GenericName=Music Player
Icon=spotify-client
TryExec=spotify
Exec=env tmux new-session -d -s my_session 'LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify' %U
Terminal=true
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify

**Comment by abba23** [comment]
Are you certain this is related to spotify-adblock and doesn't happen for you when launching Spotify normally?

**Comment by smt923** [comment]
I'm getting this too, regular spotify fine but spotify-adblock crashes on loading up, I've sort of nailed it down to this only happening on wayland (x11 still runs it fine), I get this gnarly long stack trace in logs after it crashes: https://gist.github.com/smt923/d65fdeb5f430a53dd564ba38e097087a

```
Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.1-237-tkg-pds (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series
```

**Comment by abba23** [comment]
I'll close this since it seems to be fixed for everyone in some way or another and I'm not sure I could have done anything about it anyway.

**Comment by j-frei** [comment]
I had issues with flatpak and its default com.spotify.Client.desktop app in combination with the .desktop patch from the readme page. It seems that there can be an issue with the shell/.desktop argument parsing and quotes.

The following looks a bit crazy but works as expected on my setup. (Fedora 35 amd64) At least `desktop-file-validate` doesn't complain anymore. :smile: 
Filepath: `/var/lib/flatpak/exports/share/applications/com.spotify.Client.desktop`
```
[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Online music streaming service
Comment=Access all of your favorite music
Icon=com.spotify.Client
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --file-forwarding --command=sh com.spotify.Client -c "sed s"\#"LD_PRELOAD="\#"LD_PRELOAD="\$"HOME/.spotify-adblock/spotify-adblock.so:"\#"g /app/bin/spotify | sh" @@u %U @@
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;AudioVideo;
Keywords=Music;Player;Streaming;Online;
StartupWMClass=Spotify
X-GNOME-UsesNotifications=true
X-Flatpak-Tags=proprietary;
X-Flatpak=com.spotify.Client
```
Maybe it helps anyone who has encountered similar issues...

@abba23 Super awesome hacky project! :rocket: There's a lot to learn from... :) Choosing Rust is awesome as well!
