### ISSUE TITLE
How to use LD_PRELOAD with dmenu?

### ISSUE THREAD

**Issue by abinlatheef** [abba23/spotify-adblock#90]
First of all, thank you for creating this.
I used to use this on gnome for a while now and was working flawlessly. Recently, I moved to bspwm and is using dmenu as application launcher. I can't figure out a way to call the LD_PRELOAD as dmenu is calling spotify directly from the executable (instead of open from the .desktop file where we had given the env LD_PRELOAD). Is there a workaround for this?

**Comment by abba23** [comment]
Sorry, but this seems more like problem with your dmenu configuration rather than spotify-adblock. I can't really help you with that.

**Comment by abinlatheef** [comment]
Very sorry for taking your time. I found a solution. We can just call the `.desktop` instead of calling `spotify` itself. Sorry again. 
Hope this will be of help for someone coming here for the same problem.
