### ISSUE TITLE
Unable to build on LMDE4

### ISSUE THREAD

**Issue by Rigboat27** [abba23/spotify-adblock#91]
I am trying to build this on my system for the first time, I initially had not installed cargo on my system, but after resolving that, I now just get this after running 'make'

`# cargo build --profile release
cargo build --release
    Updating crates.io index
make: *** [Makefile:14: target/release/libspotifyadblock.so] Segmentation fault (core dumped)
`
Any help would be appreciated. I have installed all requirements that are necessary.

**Comment by abba23** [comment]
Seems like a problem with rustc or cargo. Have you tried just reinstalling those?

**Comment by Rigboat27** [comment]
My bad, I reinstalled both and it was fixed. Thanks a ton.
