### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by nimaaskarian** [abba23/spotify-adblock#95]
there's a minor issue in notifications in gnome (I haven't test any other DEs).
when you click on the notification, it opens a new instance of Spotify, and its not adblocked, so it won't load properly.

**Comment by abba23** [comment]
I don't really know anything about that, since I don't use Gnome. If you created a custom desktop file in `~/.local/share/applications`, maybe try naming it the same as the original one in `/usr/share/applications`.
