### ISSUE TITLE
undefined symbol: cef_string_userfree_utf16_free

### ISSUE THREAD

**Issue by fgarcia0x0** [abba23/spotify-adblock#96]
spotify: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free

**Comment by abba23** [comment]
See #46.

**Comment by Supreme-hub** [comment]
Hey, I am also having the error, I am using `spotify 1.1.80.699.gc3dac750` published on 3 March 2022 from the snap store for Ubuntu 20.04 LTS.

**Comment by abba23** [comment]
>from the snap store

As mentioned in the readme, this does not work with the snap Spotify package.

**Comment by dxcvvxd** [comment]
i have the same error, im using the aur package on artix (it worked on arch)
